export { ReactComponent as Logo } from './icon/logo.svg'
export { ReactComponent as Cart } from './icon/cart.svg'
export { ReactComponent as Profile } from './icon/profile.svg'
export { ReactComponent as Favorite } from './icon/favorite.svg'
export { ReactComponent as NotFound } from './icon/notFound.svg'
export { ReactComponent as DeleteIcon } from './icon/delete.svg'
